/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit.*;
import static java.time.temporal.ChronoUnit.DAYS;



/**
 *
 * @author User
 */
public class DiasVividos extends javax.swing.JFrame {

    /**
     * Creates new form DiasVividos
     */
    public DiasVividos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfIAno = new javax.swing.JTextField();
        jtfIMes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfIDia = new javax.swing.JTextField();
        jbLimpar = new javax.swing.JButton();
        jbCalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfSNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(66, 28, 82));

        jtfIAno.setToolTipText("Ex: 1980");
        jtfIAno.setNextFocusableComponent(jtfIMes);
        jtfIAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIAnoKeyTyped(evt);
            }
        });

        jtfIMes.setToolTipText("Ex: 03");
        jtfIMes.setNextFocusableComponent(jtfIDia);
        jtfIMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIMesKeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Digite o ano em que nasceu:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Digite o mês em que nasceu:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Digite o dia em que nasceu:");

        jtfIDia.setToolTipText("Ex: 29");
        jtfIDia.setNextFocusableComponent(jbLimpar);
        jtfIDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIDiaKeyTyped(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.setNextFocusableComponent(jbCalcular);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jbCalcular.setText("Calcular");
        jbCalcular.setNextFocusableComponent(jtfIAno);
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });
        jbCalcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCalcularKeyPressed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Digite o seu nome:");

        jtfSNome.setToolTipText("Ex: Fulano");
        jtfSNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfIAno)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfIMes, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(jtfIDia)))
                            .addComponent(jtfSNome)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jbLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCalcular)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfSNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfIAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfIMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar)
                    .addComponent(jbCalcular))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCalcularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCalcularKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCalcular.doClick();
        }
    }//GEN-LAST:event_jbCalcularKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbLimpar.doClick();
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        // TODO add your handling code here:
        if (jtfIAno.getText().isBlank() || jtfIMes.getText().isBlank() || jtfIAno.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!");
            jtfIAno.requestFocus();
        } else {
            // Iniciando as variáveis
            String ano, mes, dia, dataString;
            LocalDate data, dataAtual = LocalDate.now();
            long qntDias;
            
            // Inserindo o valor dos campos nas variáveis
            if (Integer.parseInt(jtfIAno.getText()) > dataAtual.getYear()) {
                JOptionPane.showMessageDialog(this, "Erro, o ano de nascimento"
                        + " não pode ser maior que o ano atual.");
                jtfIAno.requestFocus();
            } else {
                ano = jtfIAno.getText();
                if (Integer.parseInt(jtfIMes.getText()) > dataAtual.getMonthValue() && Integer.parseInt(jtfIAno.getText()) == dataAtual.getYear()) {
                    JOptionPane.showMessageDialog(this, "Erro, o mês de nascimento"
                        + " não pode ser maior que o ano atual.");
                    jtfIMes.requestFocus();
                } else {
                    mes = jtfIMes.getText();
                    if (Integer.parseInt(jtfIDia.getText()) > dataAtual.getDayOfMonth() && 
                            Integer.parseInt(jtfIMes.getText()) == dataAtual.getMonthValue() && 
                            Integer.parseInt(jtfIAno.getText()) == dataAtual.getYear()) {
                        
                        JOptionPane.showMessageDialog(this, "Erro, o dia de nascimento"
                        + " não pode ser maior que o dia atual.");
                    } else {
                        dia = jtfIDia.getText();

                        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("yyyy/MM/dd");
                        dataString = ano + "/" + mes + "/" + dia;
                        data = LocalDate.parse(dataString, formatador);

//                        qntDias = DAYS.between(data.atStartOfDay(), dataAtual.atStartOfDay());
                        qntDias = data.until(dataAtual, DAYS);
                        JOptionPane.showMessageDialog(this, "Desde o dia em que você nasceu até o dia de hoje se passaram: " + qntDias + " dias");
                        
                        limpar();
                    }
                }
            }
        }
    }//GEN-LAST:event_jbCalcularActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtfIAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIAnoKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
        
        if (jtfIAno.getText().length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfIAnoKeyTyped

    private void jtfIMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIMesKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
        
        if (jtfIMes.getText().length() > 1) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfIMesKeyTyped

    private void jtfIDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIDiaKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
        
        if (jtfIDia.getText().length() > 1) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfIDiaKeyTyped

    private void jtfSNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSNomeActionPerformed

    public void limpar() {
        jtfIAno.setText("");
        jtfIMes.setText("");
        jtfIDia.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiasVividos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiasVividos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiasVividos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiasVividos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiasVividos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JTextField jtfIAno;
    private javax.swing.JTextField jtfIDia;
    private javax.swing.JTextField jtfIMes;
    public javax.swing.JTextField jtfSNome;
    // End of variables declaration//GEN-END:variables
}
